server:
  port: 9999
spring:
  application:
    name: ecommerce-website

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Bahoaivlog@45
    url: jdbc:postgresql://localhost:5432/ecommerce
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyentunglam230203@gmail.com
    password: rwjjrqwtquzaamgp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

keycloak:
  realm: ecommerce
  auth-server-url: http://localhost:8080
  resource: ecommerce
  ssl-required: none
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  credentials:
    secret: QK84b0l7Rc7xS7Qe9pYM9CXKOXEypAFJ
  public-client: true

rest-template:
  timeout: 30

redis:
  port: 6379
  host: 127.0.0.1
  database: 0
  timeout: 3600

